steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/cloudnest-rag", "."]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "cloudnest-rag"
      - "--image"
      - "gcr.io/$PROJECT_ID/cloudnest-rag"
      - "--region"
      - "$_REGION"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--service-account"
      - "$_RUNTIME_SA"
      - "--set-secrets"
      - "GEMINI_API_KEY=$_GEMINI_SECRET:latest"
      - "--set-env-vars"
      - "MODEL_NAME=gemini-2.5-flash,RESTAURANT_NAME=CloudNest Restaurant,RESTAURANT_ADDRESS=India"

substitutions:
  _REGION: asia-south1
  _GEMINI_SECRET: gemini-api-key
  _RUNTIME_SA: ""

images:
  - "gcr.io/$PROJECT_ID/cloudnest-rag"
